// *** Death to Bear ***
// © Dreadblitz
//@version=4
//
TA=input(title = "══════════ Type Of Attack ══════════", defval = true, type = input.bool)
A1=input(true, "💣 BOMB")
A2=input(true, "🔪 KNIFE")
A3=input(true, "🧨 DYNAMITE")
A4=input(true, "🗡 DAGGER")
A5=input(true, "🔫 GUN")
A6=input(true, "🧪 CHEMICAL")
min_level=input(defval=0, title="🔹 Minimum Level = ", minval=-100)

EX= input(title = "═════════ Extra ══════════", defval = true, type = input.bool)

on_symb= input(title = "Activate weapon symbols", defval = true, type = input.bool)
mod_symb= input(defval= "EMOJI", title="🔹 Type of symbol = ", options=["EMOJI", "TEXT"])

length = 8
mult = 2.0
maj_qual = 6
maj_len = 30
min_qual = 5
min_len = 5
maj = true
min = true
buy_1 = 0.0
buy_2 = 0.0
buy_3 = 0.0
buy_4 = 0.0
buy_5 = 0.0
buy_6 = 0.0

upper_s = sum(volume * (change(hlc3) <= 0 ? 0 : hlc3), 14)
lower_s = sum(volume * (change(hlc3) >= 0 ? 0 : hlc3), 14)
xmf = rsi(upper_s, lower_s)
basis = sma(ohlc4, 25)
dev = mult * stdev(ohlc4, 25)
upper = basis + dev
lower = basis - dev
OB1 = (upper + lower) / 2.0
OB2 = upper - lower
BollOsc = (ohlc4 - OB1) / OB2 * 100
xrsi = rsi(ohlc4, 14)
calc_stoch(dtb_src, length, smoothFastD) =>
    ll = lowest(low, length)
    hh = highest(high, length)
    k = 100 * (dtb_src - ll) / (hh - ll)
    sma(k, smoothFastD)
stoc = calc_stoch(ohlc4, 21, 3)
trend = (xrsi + xmf + BollOsc + stoc / 3) / 2
//
dtb_x = bar_index
dtb_y = trend
dtb_x_ = ema(dtb_x, length)
dtb_y_ = ema(dtb_y, length)
mx = stdev(dtb_x, length)
my = stdev(dtb_y, length)
dtb_c = correlation(dtb_x, dtb_y, length)
dtb_slope = dtb_c * (my / mx)
inter = dtb_y_ - dtb_slope * dtb_x_
reg_trend = dtb_x * dtb_slope + inter
//
lele(qual, len) =>
    bindex = 0.0
    sindex = 0.0
    bindex := nz(bindex[1], 0)
    sindex := nz(sindex[1], 0)
    ret = 0
    if close > close[4]
        bindex := bindex + 1
        bindex
    if close < close[4]
        sindex := sindex + 1
        sindex
    if bindex > qual and close < open and high >= highest(high, len)
        bindex := 0
        ret := -1
        ret
    if sindex > qual and close > open and low <= lowest(low, len)
        sindex := 0
        ret := 1
        ret
    return = ret
    return

major = lele(maj_qual, maj_len)
minor = lele(min_qual, min_len)
//
dtb_a = 1
dtb_cc = 10
dtb_xATR  = atr(dtb_cc)
dtb_nLoss = dtb_a * dtb_xATR
dtb_src = close
dtb_xATRTrailingStop = 0.0
dtb_xATRTrailingStop := iff(dtb_src > nz(dtb_xATRTrailingStop[1], 0) and dtb_src[1] > nz(dtb_xATRTrailingStop[1], 0), max(nz(dtb_xATRTrailingStop[1]), dtb_src - dtb_nLoss),
   iff(dtb_src < nz(dtb_xATRTrailingStop[1], 0) and dtb_src[1] < nz(dtb_xATRTrailingStop[1], 0), min(nz(dtb_xATRTrailingStop[1]), dtb_src + dtb_nLoss), 
   iff(dtb_src > nz(dtb_xATRTrailingStop[1], 0), dtb_src - dtb_nLoss, dtb_src + dtb_nLoss)))
dtb_pos = 0   
dtb_pos :=	iff(dtb_src[1] < nz(dtb_xATRTrailingStop[1], 0) and dtb_src > nz(dtb_xATRTrailingStop[1], 0), 1,
   iff(dtb_src[1] > nz(dtb_xATRTrailingStop[1], 0) and dtb_src < nz(dtb_xATRTrailingStop[1], 0), -1, nz(dtb_pos[1], 0))) 
dtb_xcolor = dtb_pos == -1 ? color.red: dtb_pos == 1 ? color.green : color.blue 
dtb_ema   = ema(dtb_src,1)
dtb_above = crossover(dtb_ema, dtb_xATRTrailingStop)
dtb_below = crossover(dtb_xATRTrailingStop, dtb_ema)
dtb_buy_a  = dtb_src > dtb_xATRTrailingStop and dtb_above 
//
if (minor == 1 and min == true and reg_trend <= min_level and A1) or (major == 1 and maj == true and reg_trend <= min_level and A1) or  (major == 1 and maj == true and minor == 1 and min == true and reg_trend <= min_level and A1)
    buy_1 := 1
if  reg_trend[0] > reg_trend[1] and reg_trend[1] > reg_trend[2] and reg_trend <= min_level and A3
    buy_2 := 1
if  crossover(trend, min_level)  and A2
    buy_3 := 1
if  crossunder(reg_trend, trend) and reg_trend <= min_level and trend <= min_level  and A6
    buy_4 := 1
if  reg_trend[0] < min_level and reg_trend[1] < min_level and reg_trend[2] < min_level and reg_trend <= min_level and reg_trend[0] > reg_trend[1] and trend <= min_level and A4
    buy_5 := 1   
if  (reg_trend[0] <= min_level or reg_trend[1] <= min_level or reg_trend[2] <= min_level or trend[0] <= min_level or trend[1] <= min_level or trend[2] <= min_level) and dtb_buy_a and A5
    buy_6 := 1  
//
plotshape(buy_1 == 1 and on_symb and mod_symb == "EMOJI", text='💣', style=shape.triangleup, location=location.belowbar, color=#32CD32, textcolor=color.black, offset=0, transp=0)
plotshape(buy_2 == 1 and on_symb and mod_symb == "EMOJI", text='🧨', style=shape.triangleup, location=location.belowbar, color=#32CD32, textcolor=color.black, offset=0, transp=0)
plotshape(buy_3 == 1 and on_symb and mod_symb == "EMOJI", text='🔪 ', style=shape.triangleup, location=location.belowbar, color=#32CD32, textcolor=color.black, offset=0, transp=0)
plotshape(buy_4 == 1 and on_symb and mod_symb == "EMOJI", text='🧪  ', style=shape.triangleup, location=location.belowbar, color=#32CD32, textcolor=color.black, offset=0, transp=0)
plotshape(buy_5 == 1 and on_symb and mod_symb == "EMOJI", text='🗡  ', style=shape.triangleup, location=location.belowbar, color=#32CD32, textcolor=color.black, offset=0, transp=0)
plotshape(buy_6 == 1 and on_symb and mod_symb == "EMOJI", text='🔫  ', style=shape.triangleup, location=location.belowbar, color=#32CD32, textcolor=color.black, offset=0, transp=0)

plotshape(buy_1 == 1 and on_symb and mod_symb == "TEXT", text='BOMB', style=shape.triangleup, location=location.belowbar, color=#32CD32, textcolor=color.black, offset=0, transp=0, size =size.tiny)
plotshape(buy_2 == 1 and on_symb and mod_symb == "TEXT", text='DYNAMITE', style=shape.triangleup, location=location.belowbar, color=#32CD32, textcolor=color.black, offset=0, transp=0, size =size.tiny)
plotshape(buy_3 == 1 and on_symb and mod_symb == "TEXT", text='KNIFE', style=shape.triangleup, location=location.belowbar, color=#32CD32, textcolor=color.black, offset=0, transp=0, size =size.tiny)
plotshape(buy_4 == 1 and on_symb and mod_symb == "TEXT", text='CHEMICAL', style=shape.triangleup, location=location.belowbar, color=#32CD32, textcolor=color.black, offset=0, transp=0, size =size.tiny)
plotshape(buy_5 == 1 and on_symb and mod_symb == "TEXT", text='DAGGER', style=shape.triangleup, location=location.belowbar, color=#32CD32, textcolor=color.black, offset=0, transp=0, size =size.tiny)
plotshape(buy_6 == 1 and on_symb and mod_symb == "TEXT", text='GUN', style=shape.triangleup, location=location.belowbar, color=#32CD32, textcolor=color.black, offset=0, transp=0, size =size.tiny)


// ALERTAS

alertcondition(buy_1 == 1,title="BOMB",message="BOMB")
alertcondition(buy_2 == 1,title="DYNAMITE",message="DYNAMITE")
alertcondition(buy_3 == 1,title="KNIFE",message="KNIFE")
alertcondition(buy_4 == 1,title="CHEMICAL",message="CHEMICAL")
alertcondition(buy_5 == 1,title="DAGGER",message="DAGGER")
alertcondition(buy_6 == 1,title="GUN",message="GUN")
alertcondition(buy_1 == 1 or buy_2 == 1 or buy_3 == 1 or buy_4 == 1 or buy_5 == 1 or buy_6 == 1,title="ANY WEAPON",message="ANY WEAPON")
