//@version=4
study(shorttitle="Kajetan's Price Bands", title="Kajetan's Price Bands", overlay=true)
length = input(20, minval=1)
src = input(close, title="BB Source")
mult = input(2.0, minval=0.001, maxval=50)
basis = sma(src, length)
dev = mult * stdev(src, length)
upper = basis + dev
lower = basis - dev
plot(basis, color=#ff0000, linewidth=2, transp=0)
p1 = plot(upper, color=color.teal, linewidth=2, transp=0)
p2 = plot(lower, color=color.teal, linewidth=2, transp=0)

dc_length = input(20, minval=1)
dc_lower = lowest(dc_length)
dc_upper = highest(dc_length)
dc_basis = avg(dc_upper, dc_lower)
plot(dc_basis, color=#FFA500, linewidth=2, transp=0)