//@version=4
study(title="Kajetan's Trend Change", shorttitle="Kajetan's Trend Change")

// Aroon

length = input(14, minval=1, title="Aroon Length")
upper = 100 * (highestbars(high, length+1) + length)/length
lower = 100 * (lowestbars(low, length+1) + length)/length
plot(upper, color=#0090d9, linewidth=2, transp=0)
plot(lower, color=#ffc200, linewidth=2, transp=0)

// Chop and Explode RSI
src = close
len = input(14, minval=1, title="RSI Length")
up = rma(max(change(src), 0), len)
down = rma(-min(change(src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - 100 / (1 + up / down)

plot(rsi, color=color.white, linewidth=2)

change1 = rsi > 60 ? #00ff1c : na
change2 = rsi < 40 ? #ff0000 : na

p1 = plot(rsi, style=plot.style_linebr, linewidth=2, color=change1, transp=0)
p2 = plot(rsi, style=plot.style_linebr, linewidth=2, color=change2, transp=0)

band1 = hline(70)
band2 = hline(30)
band3 = hline (60, linestyle=hline.style_dotted)
band4 = hline (40, linestyle=hline.style_dotted)
midline = hline(50, linestyle=hline.style_solid)

