//@version=4
study(title="Kajetan's Trend Change", shorttitle="Kajetan's Trend Change")

// Aroon

length = input(14, minval=1, title="Aroon Length")
upper = 100 * (highestbars(high, length+1) + length)/length
lower = 100 * (lowestbars(low, length+1) + length)/length
plot(upper, color=#0090d9, linewidth=2, transp=0)
plot(lower, color=#ffc200, linewidth=2, transp=0)

// Chop and Explode RSI
src = close
len = input(14, minval=1, title="RSI Length")
up = rma(max(change(src), 0), len)
down = rma(-min(change(src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - 100 / (1 + up / down)

plot(rsi, color=color.white, linewidth=2)

change1 = rsi > 60 ? #00ff1c : na
change2 = rsi < 40 ? #ff0000 : na

p1 = plot(rsi, style=plot.style_linebr, linewidth=2, color=change1, transp=0)
p2 = plot(rsi, style=plot.style_linebr, linewidth=2, color=change2, transp=0)

band1 = hline(70)
band2 = hline(30)
band3 = hline (60, linestyle=hline.style_dotted)
band4 = hline (40, linestyle=hline.style_dotted)
midline = hline(50, linestyle=hline.style_solid)

// Chop Zone

//@version=4

colorTurquoise = #34dddd
colorDarkGreen = #006400
colorPaleGreen = #98fb98
colorLime = color.lime
colorDarkRed = #8B0000
colorRed = color.red
colorOrange = color.orange
colorLightOrange = #ffc04c
colorYellow = color.yellow

source = close
avg = hlc3

pi = atan(1) * 4
periods = 30
highestHigh = highest(periods)
lowestLow = lowest(periods)
range = 25 / (highestHigh - lowestLow) * lowestLow

ema34 = ema(source, 34)
x1_ema34 = 0
x2_ema34 = 1
y1_ema34 = 0
y2_ema34 = (ema34[1] - ema34) / avg * range
c_ema34 = sqrt((x2_ema34 - x1_ema34)*(x2_ema34 - x1_ema34) + (y2_ema34 - y1_ema34)*(y2_ema34 - y1_ema34))
emaAngle_1 = round(180 * acos((x2_ema34 - x1_ema34)/c_ema34) / pi)
emaAngle = iff(y2_ema34 > 0, - emaAngle_1, emaAngle_1)

chopZoneColor = emaAngle >= 5 ? colorTurquoise : emaAngle < 5 and emaAngle >= 3.57 ? colorDarkGreen : emaAngle < 3.57 and emaAngle >= 2.14 ? colorPaleGreen : emaAngle < 2.14 and emaAngle >= .71 ? colorLime : emaAngle <= -1 * 5 ? colorDarkRed : emaAngle > -1 * 5 and emaAngle <= -1 * 3.57 ? colorRed : emaAngle > -1 * 3.57 and emaAngle <= -1 * 2.14 ? colorOrange : emaAngle > -1 * 2.14 and emaAngle <= -1 * .71 ? colorLightOrange : colorYellow

plot(-10, color=chopZoneColor, style=plot.style_line, linewidth=3, transp=0)
