//@version=4
study("Kajetan's Moving Averages", overlay=true)

// MAs
ma_1 = input(50, title="MA 1")
ma_2 = input(100, title="MA 2")
ma_3 = input(200, title="MA 3")
plot(sma(close, ma_1), color=#7705b9, transp=0, linewidth=2, title="MA 1")
plot(sma(close, ma_2), color=#0090f7, transp=0, linewidth=2, title="MA 2")
plot(sma(close, ma_3), color=#ffc200, transp=0, linewidth=2, title="MA 3")

// EMAs
ema_1 = input(12, title="EMA 1")
ema_2 = input(26, title="EMA 2")
plot(ema(close, ema_1), color=#00bfd8, transp=0, linewidth=2, title="EMA 1")
plot(ema(close, ema_2), color=#ff0057, transp=0, linewidth=2, title="EMA 2")

// HMA
//HMA = WMA(2*WMA(n/2) − WMA(n)),sqrt(n))
f_hma(_src, _length) =>
    _return = wma(2 * wma(_src, _length / 2) - wma(_src, _length), round(sqrt(_length)))
    _return
hma_length = input(200, title="HMA")
plot(series=f_hma(close, hma_length), title='HMA', color=#ff5e00, transp=0, linewidth=2)

// WMA
wma_length = input(200, minval=1, title="WMA")
plot(wma(close, wma_length), linewidth=2, color=#9598a2, transp=0, title="WMA")

// VWAP
// plot(vwap(close), color=#ffffff, transp=0, linewidth=2, title="VWAP", trackprice=true)
