//@version=4

//
study(shorttitle="Kajetan's Oscillator", title="Kajetan's WaveTrend Oscilador", overlay=false)

n1 = input(10, "Channel Length")
n2 = input(21, "Moving Period")
reaction_wt  = input(defval=1, title="Reaction in change of direction", minval=1)

obl = input(53, "Overbought Level", minval=0.0)
osl = input(-53, "Oversold Level", maxval=-0.0)

ventas_en_sobre_compra = input(true, title="Solo Ventas en Sobre Compra")
compras_en_sobre_venta = input(true, title="Solo Compras en Sobre Venta")

signal = input(true, title="Show Signal Line")
barras = input(true, title="Pintar Barras")
div_reg_al= input(true, title="Ver Divergencias Regulares Alcistas")
div_reg_ba= input(true, title="Ver Divergencias Regulares Bajistas")
div_ocu_al= input(false, title="Ver Divergencias Ocultas Alcistas")
div_ocu_ba= input(false, title="Ver Divergencias Ocultas Bajistas")
etiquetas= input(true, title="Ver Etiquetas De Divergencias")
// amme= input(false, title="Activar media movil Extra para WT")

obl1 =  obl
obl2 =  obl+5
obl3 =  obl+10
obl4 =  obl+15
obl5 =  obl+20
obl6 =  obl+25
obl7 =  obl+30
obl8 =  obl+35

osl1 =  osl-5
osl2 =  osl-10
osl3 =  osl-15
osl4 =  osl-20
osl5 =  osl-25
osl6 =  osl-30
osl7 =  osl-35
osl8 =  osl-40

blanco=#FDFEFE
negro=#000000
rojo=#FF0000
verde=#00FF13
verde_fuerte=#0AAC00
verde_1=#00FF00
celeste=#00D4FF
celeste_1=#009BBA
naranja=#FF8B00
amarillo=#FFFB00
azul=#0066FF
rosa=#FF33CC

ap = hlc3
esa = ema(ap, n1)
d = ema(abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * d)
tci = ema(ci, n2)

wt1 = tci
wt2 = sma(wt1,4)

direction = 0
direction := rising(wt1,reaction_wt) ? 1 : falling(wt1,reaction_wt) ? -1 : nz(direction[1])
cambio_direccion= change(direction,1)
pcol = direction>0 ? verde_fuerte : direction<0 ? rojo : na

plot(wt1, title='WaveTrend', color=#83c9fc, linewidth=1, style=plot.style_area, transp=0)

plot(signal ? wt2 : na, style=plot.style_area, color=#163ba4, linewidth=1, title="Signal", transp=10)

// signal1 = crossover(wt1, wt2) and wt1 < osl
// signal2 = crossunder(wt1, wt2) and wt1 > obl

// plotshape(signal1 ? wt1 : na, style=shape.xcross, location=location.absolute, size=size.small, color=color.lime)
// plotshape(signal2 ? wt1 : na, style=shape.xcross, location=location.absolute, size=size.small, color=color.red)

plot(0, title='Level 0', color=#ffffff, linewidth=1, style=plot.style_line, transp=0)

pobl1=plot(obl1, title='Nivel 1 Sobre Compra', color=rojo, linewidth=1, style=plot.style_line, transp=100)
pobl2=plot(obl2, title='Nivel 2 Sobre Compra', color=rojo, linewidth=1, style=plot.style_line, transp=100)
pobl3=plot(obl3, title='Nivel 3 Sobre Compra', color=rojo, linewidth=1, style=plot.style_line, transp=100)
pobl4=plot(obl4, title='Nivel 4 Sobre Compra', color=rojo, linewidth=1, style=plot.style_line, transp=100)
pobl5=plot(obl5, title='Nivel 5 Sobre Compra', color=rojo, linewidth=1, style=plot.style_line, transp=100)
pobl6=plot(obl6, title='Nivel 6 Sobre Compra', color=rojo, linewidth=1, style=plot.style_line, transp=100)
pobl7=plot(obl7, title='Nivel 7 Sobre Compra', color=rojo, linewidth=1, style=plot.style_line, transp=100)
pobl8=plot(obl8, title='Nivel 8 Sobre Compra', color=rojo, linewidth=1, style=plot.style_line, transp=100)

fill(pobl1, pobl2, color=rojo, transp=75)
fill(pobl2, pobl3, color=rojo, transp=70)
fill(pobl3, pobl4, color=rojo, transp=65)
fill(pobl4, pobl5, color=rojo, transp=60)
fill(pobl5, pobl6, color=rojo, transp=55)
fill(pobl6, pobl7, color=rojo, transp=50)
fill(pobl7, pobl8, color=rojo, transp=45)

posl1=plot(osl1, title='Nivel 1 Sobre Venta', color=verde, linewidth=1, style=plot.style_line, transp=100)
posl2=plot(osl2, title='Nivel 2 Sobre Venta', color=verde, linewidth=1, style=plot.style_line, transp=100)
posl3=plot(osl3, title='Nivel 3 Sobre Venta', color=verde, linewidth=1, style=plot.style_line, transp=100)
posl4=plot(osl4, title='Nivel 4 Sobre Venta', color=verde, linewidth=1, style=plot.style_line, transp=100)
posl5=plot(osl5, title='Nivel 5 Sobre Venta', color=verde, linewidth=1, style=plot.style_line, transp=100)
posl6=plot(osl6, title='Nivel 6 Sobre Venta', color=verde, linewidth=1, style=plot.style_line, transp=100)
posl7=plot(osl7, title='Nivel 7 Sobre Venta', color=verde, linewidth=1, style=plot.style_line, transp=100)
posl8=plot(osl8, title='Nivel 8 Sobre Venta', color=verde, linewidth=1, style=plot.style_line, transp=100)

fill(posl1, posl2, color=verde, transp=75)
fill(posl2, posl3, color=verde, transp=70)
fill(posl3, posl4, color=verde, transp=65)
fill(posl4, posl5, color=verde, transp=60)
fill(posl5, posl6, color=verde, transp=55)
fill(posl6, posl7, color=verde, transp=50)
fill(posl7, posl8, color=verde, transp=45)

midpoint = (obl + osl) / 2
ploff = (obl - midpoint) / 8

venta = crossunder(wt1, wt2) and wt1 >= obl and ventas_en_sobre_compra == true
venta_1 = crossunder(wt1, wt2) and ventas_en_sobre_compra == false

compra = crossover(wt1, wt2) and wt1 <= osl and compras_en_sobre_venta == true
compra_1 = crossover(wt1, wt2) and compras_en_sobre_venta == false

plotshape(venta ? wt2[1] : na, location=location.absolute, style=shape.xcross, color=rojo, size=size.small, title="Ventas En Sobre Compra", transp=0)
plotshape(venta_1 ? wt2[1] : na, location=location.absolute, style=shape.xcross, color=rojo, size=size.small, title="Todas Las Ventas", transp=0)

plotshape(compra ? wt2[1] : na, location=location.absolute, style=shape.xcross, color=verde_fuerte, size=size.small, title="Compras En Sobre Venta", transp=0)
plotshape(compra_1 ? wt2[1] : na, location=location.absolute, style=shape.xcross, color=verde_fuerte, size=size.small, title="Todas Las Compras", transp=0)

direction_ch_up = crossover(wt1, wt2) and wt1 > osl
direction_ch_down = crossunder(wt1, wt2) and wt1 < obl

plotshape(direction_ch_up ? wt2[1] : na, location=location.absolute, style=shape.circle, color=verde_fuerte, size=size.tiny, title="Direction Change Upwards", transp=0)
plotshape(direction_ch_down ? wt2[1] : na, location=location.absolute, style=shape.circle, color=rojo, size=size.tiny, title="Direction Change Downwards", transp=0)

barcolor((barras == true and compra == true) or (barras == true and compra_1 == true)  ? verde_1 : na)
barcolor((barras == true and venta == true) or (barras == true and venta_1 == true)  ? rojo : na)

/////// Divergencias ///////

f_top_fractal(_src)=>_src[4] < _src[2] and _src[3] < _src[2] and _src[2] > _src[1] and _src[2] > _src[0]
f_bot_fractal(_src)=>_src[4] > _src[2] and _src[3] > _src[2] and _src[2] < _src[1] and _src[2] < _src[0]
f_fractalize(_src)=>f_top_fractal(_src) ? 1 : f_bot_fractal(_src) ? -1 : 0

fractal_top1 = f_fractalize(wt1) > 0 ? wt1[2] : na
fractal_bot1 = f_fractalize(wt1) < 0 ? wt1[2] : na

high_prev1  = valuewhen(fractal_top1, wt1[2], 0)[2]
high_price1 = valuewhen(fractal_top1, high[2], 0)[2]
low_prev1   = valuewhen(fractal_bot1, wt1[2], 0)[2]
low_price1  = valuewhen(fractal_bot1, low[2], 0)[2]

regular_bearish_div1 = fractal_top1  and high[2] > high_price1 and wt1[2] < high_prev1 and div_reg_ba == true
hidden_bearish_div1  = fractal_top1  and high[2] < high_price1 and wt1[2] > high_prev1 and div_ocu_ba == true
regular_bullish_div1 = fractal_bot1  and low[2]  < low_price1  and wt1[2] > low_prev1 and div_reg_al == true
hidden_bullish_div1  = fractal_bot1  and low[2]  > low_price1  and wt1[2] < low_prev1 and div_ocu_al == true

col1 = regular_bearish_div1 ? rojo : hidden_bearish_div1 ? rojo : na
col2 = regular_bullish_div1 ? verde_fuerte : hidden_bullish_div1 ? verde_fuerte  : na

plot(title='Divergencias Bajistas', series = fractal_top1 ? wt1[2] : na, color=col1, linewidth=2, offset=-2, transp=0)
plot(title='Divergencias Alcistas', series = fractal_bot1 ? wt1[2] : na, color=col2, linewidth=2, offset=-2, transp=0)

plotshape(regular_bearish_div1 and div_reg_ba and etiquetas  ? wt1[1] + ploff*1 : na, title="Divergencia Regular Bajista", text="🐻 R", location=location.absolute, style=shape.labeldown, size=size.tiny, color=rojo, textcolor=blanco,offset=-2, transp=0)
plotshape(hidden_bearish_div1 and div_ocu_ba and etiquetas  ? wt1[1] + ploff*1 : na, title="Divergencia Oculta Bajista", text="🐻 O", location=location.absolute, style=shape.labeldown, size=size.tiny, color=rojo, textcolor=blanco,offset=-2, transp=0)

plotshape(regular_bullish_div1 and div_reg_al and etiquetas  ? wt1[1] - ploff*1 : na, title="Divergencia Regular Alcista", text="🐂 R", location=location.absolute, style=shape.labelup, size=size.tiny, color=verde_fuerte, textcolor=blanco,offset=-2, transp=0)
plotshape(hidden_bullish_div1 and div_ocu_al and etiquetas  ? wt1[1] - ploff*1 : na, title="Divergencia Oculta Alcista", text="🐂 O", location=location.absolute, style=shape.labelup, size=size.tiny, color=verde_fuerte, textcolor=blanco,offset=-2, transp=0)


//// Media extra aplicada a WT ///

ma_type = input(defval="EMA", title="MA Extra Tipo: ", options=["SMA", "EMA", "WMA", "VWMA", "SMMA", "DEMA", "TEMA", "HullMA", "ZEMA", "TMA", "SSMA"])
ma_len = input(defval=200, title="MA Extra Periodo", minval=1)
ma_src = wt1
reaction = input(defval=1, title="MA Extra Reaccion", minval=1)

// SuperSmoother filter
// © 2013  John F. Ehlers
variant_supersmoother(src, len) =>
    a1 = exp(-1.414 * 3.14159 / len)
    b1 = 2 * a1 * cos(1.414 * 3.14159 / len)
    c2 = b1
    c3 = -a1 * a1
    c1 = 1 - c2 - c3
    v9 = 0.0
    v9 := c1 * (src + nz(src[1])) / 2 + c2 * nz(v9[1]) + c3 * nz(v9[2])
    v9

variant_smoothed(src, len) =>
    v5 = 0.0
    sma_1 = sma(src, len)
    v5 := na(v5[1]) ? sma_1 : (v5[1] * (len - 1) + src) / len
    v5

variant_zerolagema(src, len) =>
    ema1 = ema(src, len)
    ema2 = ema(ema1, len)
    v10 = ema1 + ema1 - ema2
    v10

variant_doubleema(src, len) =>
    v2 = ema(src, len)
    v6 = 2 * v2 - ema(v2, len)
    v6

variant_tripleema(src, len) =>
    v2 = ema(src, len)
    v7 = 3 * (v2 - ema(v2, len)) + ema(ema(v2, len), len)
    v7

variant(type, src, len) =>
    ema_1 = ema(src, len)
    wma_1 = wma(src, len)
    vwma_1 = vwma(src, len)
    variant_smoothed__1 = variant_smoothed(src, len)
    variant_doubleema__1 = variant_doubleema(src, len)
    variant_tripleema__1 = variant_tripleema(src, len)
    wma_2 = wma(src, len / 2)
    wma_3 = wma(src, len)
    wma_4 = wma(2 * wma_2 - wma_3, round(sqrt(len)))
    variant_supersmoother__1 = variant_supersmoother(src, len)
    variant_zerolagema__1 = variant_zerolagema(src, len)
    sma_1 = sma(src, len)
    sma_2 = sma(sma_1, len)
    sma_3 = sma(src, len)
    type == "EMA" ? ema_1 : type == "WMA" ? wma_1 : 
       type == "VWMA" ? vwma_1 : type == "SMMA" ? variant_smoothed__1 : 
       type == "DEMA" ? variant_doubleema__1 : type == "TEMA" ? variant_tripleema__1 : 
       type == "HullMA" ? wma_4 : type == "SSMA" ? variant_supersmoother__1 : 
       type == "ZEMA" ? variant_zerolagema__1 : type == "TMA" ? sma_2 : sma_3


// === Moving Average
// ma_series = variant(ma_type, ma_src, ma_len)

// direction_a = 0
// falling_1 = falling(ma_series, reaction)
// direction_a := rising(ma_series, reaction) ? 1 : falling_1 ? -1 : nz(direction_a[1])
// change_direction = change(direction_a, 1)

// pcol_a = direction_a > 0 ? #2E8B57 : direction_a < 0 ? #FF4500 : na
// plot(amme?ma_series:na, color=pcol_a, style=plot.style_line, join=true, linewidth=3, transp=10, title="MA PLOT")

/////// Alertas en Ingles //////

alertcondition(venta,title="Overbought Sales")
alertcondition(venta_1,title="All Sales")

alertcondition(compra,title="Oversold Buys")
alertcondition(compra_1,title="All Buys")

alertcondition(venta or compra,title="Buys/Sales Overbought/Oversold")
alertcondition(venta_1 or compra_1,title="All Sales/Buys")

alertcondition(cambio_direccion,title="WT Direction Change")
