// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © cajetan.puchalski

//@version=4
strategy("TrueTrend Strategy", overlay=true)

zero_line = 0

length = input(70, minval=1, title="Trend CCI Length")
cci = (close - sma(close, length)) / (0.015 * dev(close, length))

longCondition = crossover(cci, zero_line)
if (longCondition)
    strategy.entry("LongID", strategy.long)

shortCondition = crossunder(cci, zero_line)
if (shortCondition)
    strategy.entry("ShortID", strategy.short)